### ISSUE TITLE
magnetX的1.1.0到1.1.5在macOS的10.14.4都闪退

### ISSUE THREAD

**Issue by ajsong** [youusername/magnetX#7]
magnetX的1.1.0到1.1.5在macOS的10.14.4都闪退哦

**Comment by luhengqi** [comment]
在 macOS Mojave 10.14 及以上系统会出现闪退报错无法使用的情况，可在终端输入以下代码即可运行
`sudo codesign --force --deep --sign - 文件位置（直接将应用拖进去即可）`
